keys:
  - &admin 3AC6F170F01133CE393BCD94BE948AFD7E7873BE
  - &elios 0C143D8AFF5FBCD2293897658E66EDB0546158DF
  - &hel1 0f0c4c2f9877cb8a53efadacb90613a2af502673
creation_rules:
  - path_regex: secrets.enc.yml$
    key_groups:
      - pgp:
          - *admin
          - *elios
          - *hel1
