---
- hosts: k8s_kubectl
  roles:
    - role: githubixx.kubectl
      tags: role-kubectl
- hosts: k8s_ca
  roles:
    - role: githubixx.cfssl
      tags: role-cfssl
    - role: githubixx.kubernetes-ca
      tags: role-kubernetes-ca
    - role: githubixx.kubernetes-ca
      tags: role-kubernetes-ca
- hosts: k8s_etcd
  roles:
    - role: githubixx.etcd
      tags: role-etcd
- hosts: k8s_controller
  roles:
    - role: githubixx.kubernetes-controller
      tags: role-kubernetes-controller
- hosts: k8s
  roles:
    - role: githubixx.harden-linux
      tags: role-harden-linux
- hosts: all
  roles:
    - role: githubixx.peervpn
      tags: role-peervpn
