---
- hosts: localhost
  gather_facts: no
  roles:
    - role: scaleway-provision
      tags: role-provision
- hosts: localhost
  become: yes
  gather_facts: no
  roles:
    - role: harden-linux
      tags: role-harden-linux
    - role: githubixx.peervpn
      tags: role-peervpn
- hosts: k8s
  vars:
    ansible_user: ubuntu
  gather_facts: no
  roles:
    - role: harden-linux
      tags: role-harden-linux
- hosts: all
  become: yes
  roles:
    - role: peervpn
      tags: role-peervpn
- hosts: k8s_ca
  become: yes
  roles:
    - role: cfssl
      tags: role-cfssl
    - role: kubernetes-ca
      tags: role-kubernetes-ca
- hosts: k8s_kubectl
  become: yes
  roles:
    - role: kubectl
      tags: role-kubectl
- hosts: k8s_etcd
  roles:
    - role: etcd
      tags: role-etcd
- hosts: k8s_master
  roles:
    - role: kubernetes-controller
      tags: role-kubernetes-controller
- hosts: k8s_worker
  roles:
    - role: githubixx.kubernetes-worker
      tags: role-kubernetes-worker
- hosts: k8s
  roles:
    - role: githubixx.flanneld
      tags: role-kubernetes-flanneld
    - role: githubixx.docker
      tags: role-docker
