---
- hosts: localhost
  roles:
    - role: scaleway-provision
      tags: role-provision
- hosts: k8s_kubectl
  roles:
    - role: githubixx.kubectl
      tags: role-kubectl
- hosts: k8s_ca
  roles:
    - role: githubixx.cfssl
      tags: role-cfssl
    - role: githubixx.kubernetes-ca
      tags: role-kubernetes-ca
- hosts: k8s_etcd
  roles:
    - role: githubixx.etcd
      tags: role-etcd
- hosts: k8s_controller
  roles:
    - role: githubixx.kubernetes-controller
      tags: role-kubernetes-controller
- hosts: k8s_worker
  roles:
    - role: githubixx.kubernetes-worker
      tags: role-kubernetes-worker
- hosts: k8s
  roles:
    - role: githubixx.flanneld
      tags: role-kubernetes-flanneld
    - role: githubixx.docker
      tags: role-docker
- hosts: all
  roles:
    - role: githubixx.harden-linux
      tags: role-harden-linux
    - role: githubixx.peervpn
      tags: role-peervpn
