{
 "title": "Web traffic",
 "description": "hel1 nginx access logs per virtual host.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "banditlair" },
   { "name": "vhost", "label": "Virtual host (regex)", "query": ".*" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 2 },
   "options": {
    "content": "Built from nginx access logs. The virtual host and timings are only logged since the log format change, so older lines are ignored."
   }
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 2, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" [$__range]))"
    }
   ]
  },
  {
   "title": "Server errors (5xx)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 2, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" | status >= 500 [$__range])) / sum(count_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" [$__range]))"
    }
   ]
  },
  {
   "title": "Data sent",
   "type": "stat",
   "gridPos": { "x": 12, "y": 2, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" | unwrap bytes [$__range]))"
    }
   ]
  },
  {
   "title": "Distinct clients",
   "type": "stat",
   "gridPos": { "x": 18, "y": 2, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (ip) (count_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" [$__range])))"
    }
   ]
  },
  {
   "title": "Requests per second by virtual host (top 10)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (vhost) (rate({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" [$__auto])))",
     "legendFormat": "{{vhost}}"
    }
   ]
  },
  {
   "title": "Responses by status class",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (class) (rate({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" | label_format class=`{{ substr 0 1 .status }}xx` [$__auto]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "95th percentile request time by virtual host (top 10)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 15, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, quantile_over_time(0.95, {host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" | unwrap request_time | __error__=\"\" [$__auto]) by (vhost))",
     "legendFormat": "{{vhost}}"
    }
   ]
  },
  {
   "title": "Server errors by virtual host",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 15, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (vhost, status) (count_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" | status >= 500 [$__auto]))",
     "legendFormat": "{{vhost}} {{status}}"
    }
   ]
  },
  {
   "title": "Virtual hosts (time range)",
   "type": "table",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum by (vhost) (count_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" [$__range]))"
    },
    {
     "expr": "sum by (vhost) (count_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" | status >= 400 | status < 500 [$__range]))"
    },
    {
     "expr": "sum by (vhost) (count_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" | status >= 500 [$__range]))"
    },
    {
     "expr": "quantile_over_time(0.95, {host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" | unwrap request_time | __error__=\"\" [$__range]) by (vhost)"
    },
    {
     "expr": "sum by (vhost) (sum_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" | unwrap bytes | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "Top 404 paths (time range)",
   "type": "table",
   "gridPos": { "x": 0, "y": 32, "w": 14, "h": 10 },
   "targets": [
    {
     "expr": "topk(20, sum by (vhost, uri) (count_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" | status = 404 [$__range])))"
    }
   ]
  },
  {
   "title": "Top clients (time range)",
   "type": "table",
   "gridPos": { "x": 14, "y": 32, "w": 10, "h": 10 },
   "targets": [
    {
     "expr": "topk(20, sum by (ip) (count_over_time({host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/access.log\"} | pattern `<ip> - <_> [<_>] \"<method> <uri> <_>\" <status> <bytes> \"<_>\" \"<_>\" \"<vhost>\" <request_time> <_>` | vhost != \"\" | vhost =~ \"$vhost\" [$__range])))"
    }
   ]
  },
  {
   "title": "nginx errors",
   "type": "logs",
   "gridPos": { "x": 0, "y": 42, "w": 24, "h": 10 },
   "targets": [
    {
     "expr": "{host=\"hel1\", job=\"nginx\", filename=\"/var/log/nginx/error.log\"} |~ \"\\\\[(error|crit|alert|emerg)\\\\]\"",
     "maxLines": 200
    }
   ]
  }
 ]
}