{
 "title": "dmarc dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dmarc_total[$__range]))"
    }
   ]
  },
  {
   "title": "# compliant",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(dmarc_compliant_total[$__range]))"
    }
   ]
  },
  {
   "title": "# reject",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dmarc_reject_total[$__range]))"
    }
   ]
  },
  {
   "title": "# quarantine",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dmarc_quarantine_total[$__range]))"
    }
   ]
  },
  {
   "title": "% compliant",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(dmarc_compliant_total[$__range]))/sum(increase(dmarc_total[$__range]))"
    }
   ]
  },
  {
   "title": "% reject",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dmarc_reject_total[$__range]))/sum(increase(dmarc_total[$__range]))"
    }
   ]
  },
  {
   "title": "% quarantine",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dmarc_quarantine_total[$__range]))/sum(increase(dmarc_total[$__range]))"
    }
   ]
  },
  {
   "title": "# by reporter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dmarc_compliant_total[$__rate_interval])) by (reporter)",
     "legendFormat": "Compliant by {{reporter}}"
    },
    {
     "expr": "sum(increase(dmarc_reject_total[$__rate_interval])) by (reporter)",
     "legendFormat": "Reject by {{reporter}}"
    }
   ]
  },
  {
   "title": "# by sender domain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dmarc_compliant_total[$__rate_interval])) by (dkim_domain)",
     "legendFormat": "Compliant from {{dkim_domain}}"
    },
    {
     "expr": "sum(increase(dmarc_reject_total[$__rate_interval])) by (dkim_domain)",
     "legendFormat": "Rejected from {{dkim_domain}}"
    }
   ]
  }
 ]
}